### ISSUE TITLE
ImageFrameView的第107行是否应该是loadInThread(file.listFiles())

### ISSUE THREAD

**Issue by wujianyin** [Mr-wangyong/ImageFrame#1]
第105行到顶108行代码
`} else {
        index++;
        loadInThread(files);
 }`
是否应该改为这样：
`} else if(file.isDirectory()){
        index++;
        loadInThread(file.listFiles());
 }`

**Comment by Mr-wangyong** [comment]
谢谢您的提醒,其实 else后面假设该文件不是图片(Mac压缩后有个macosx的隐藏文件),马上循环调到下一个文件上,因下一个文件还是走这个方法,还是会判断是不是图片,所以逻辑上是对的,并无差错
