### ISSUE TITLE
部分机型播放速度过快

### ISSUE THREAD

**Issue by ZXY0552** [Mr-wangyong/ImageFrame#19]
https://github.com/Mr-wangyong/ImageFrame/blob/f46df90651be70e2ecb39186e131af6f14ffd7da/imageframelibs/src/main/java/com/mrwang/imageframe/ImageFrameHandler.java#L298
这里好像有点问题，uptimeMillis是不是应该传long类型？

**Comment by Mr-wangyong** [comment]
是因为丢帧吧 这里的确是 long 类型，底层会做类型转换，跟主线程的 handler 执行速度有关

**Comment by ZXY0552** [comment]
会做数据类型转换但是由于传的是int，会不会出现精度丢失问题？我这边遇到的问题不是丢帧，是handler发送出去的消息不会延迟，立即就执行了，导致图片绘制的时候帧数过快。
