### ISSUE TITLE
加载文件图片不会轮播

### ISSUE THREAD

**Issue by a10655** [Mr-wangyong/ImageFrame#6]
如题， 加载手机sdcard的图片文件，执行一次帧动画， 然后就不会再执行，loadInThreadFromFile(File[] files)方法是一直在反复执行的。。。

**Comment by Mr-wangyong** [comment]
尝试过加载demo里面的Resource文件了吗 看看能否播放??

**Comment by Mr-wangyong** [comment]
可以尝试打印出来看看每个文件的名称

**Comment by a10655** [comment]
加载demo里的Resource没有问题， 然后加载sdcard卡图片文件的时候， 只能播放一次，   在控制台打印的文件名字是跟第一次一样的

**Comment by vampire184** [comment]
加载sd卡里面的图片，确实只能播放一次

**Comment by Mr-wangyong** [comment]
最新的V1.3版本已经修复了这个问题了,加入了流式API,感谢您的反馈
