### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by longshiming** [Mr-wangyong/ImageFrame#7]
#1944 java.util.ConcurrentModificationException
com.example.imageframelibs.ImageFrame.WorkHandler$1.void handleMessage(android.os.Message)(SourceFile:34)

解决方案
该异常表示迭代器迭代过程中，迭代的对象发生了改变，如数据项增加或删除。
[解决方案]：由于迭代对象不是线程安全，在迭代的过程中，会检查modCount是否和初始modCount即expectedModCount一致，如果不一致，则认为数据有变化，迭代终止并抛出异常。常出现的场景是，两个线程同时对集合进行操作，线程1对集合进行遍历，而线程2对集合进行增加、删除操作，此时将会发生ConcurrentModificationException异常。
具体方法：多线程访问时要增加同步锁，或者建议使用线程安全的集合：
1. 使用ConcurrentHashMap替换HashMap，CopyOnWriteArrayList替换ArrayList；
2. 或者使用使用Vector替换ArrayList，Vector是线程安全的。Vector的缺点：大量数据操作时，由于线程安全，性能比ArrayList低.

**Comment by Mr-wangyong** [comment]
v1.3版本已修复此问题,谢谢反馈
